### ISSUE TITLE
Version compatible with typesense v. 0.24

### ISSUE THREAD

**Issue by CasperNH** [typesense/typesense-php#37] opened 2023-03-30 17:01 UTC
## Description

Needs to be updated to be compatible with Typesense v. 0.24

## Metadata

Typesense V 0.24

**OS**:

**Comment by karakhanyans** [comment] 2023-08-24 08:39
@CasperNH the issue is fixed with the latest release.

**Closed by karakhanyans** 2023-08-24 08:39 UTC
