### ISSUE TITLE
`utf8_encode()` is deprecated in PHP 8.2

### ISSUE THREAD

**Issue by ivan-wolf** [typesense/typesense-php#43] opened 2023-08-15 18:10 UTC
## Description

The method `Keys::generateScopedSearchKey()` contains the deprecated `utf8_encode()` call.

https://github.com/typesense/typesense-php/blob/903b7226400ce64930226b0f259b56bac6476735/src/Keys.php#L58

## Steps to reproduce

Call the mentioned method.

## Expected Behavior

Don't trigger the deprecation warning.

## Actual Behavior

The deprecation warning is triggered.

**Comment by karakhanyans** [comment] 2023-08-24 08:39
@ivan-wolf the issue is fixed in the latest release.

**Closed by karakhanyans** 2023-08-24 08:39 UTC
